# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_phone', models.DecimalField(decimal_places=4, max_digits=14, max_length=200)),
                ('org_email', models.EmailField(max_length=50)),
                ('org_address', models.CharField(max_length=500)),
            ],
        ),
    ]
